server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show_sql: true
    properties:
      hibernate:
        format_sql: true

#  datasource:
#    url: jdbc:h2:tcp://localhost/~/testDB
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  datasource:
    url: jdbc:mariadb://localhost:3306/querydsl
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver


  h2:
    console:
      enabled: true
      path: /h2-console
